[2024-06-06T15:55:37.622+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T15:55:37.641+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_3 manual__2024-06-06T10:25:06.141092+00:00 [queued]>
[2024-06-06T15:55:37.648+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_3 manual__2024-06-06T10:25:06.141092+00:00 [queued]>
[2024-06-06T15:55:37.649+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-06-06T15:55:37.666+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collect_data_3> on 2024-06-06 10:25:06.141092+00:00
[2024-06-06T15:55:37.670+0530] {standard_task_runner.py:63} INFO - Started process 36667 to run task
[2024-06-06T15:55:37.675+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'collect_data_3', 'manual__2024-06-06T10:25:06.141092+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpykwwewfs']
[2024-06-06T15:55:37.677+0530] {standard_task_runner.py:91} INFO - Job 59: Subtask collect_data_3
[2024-06-06T15:55:37.758+0530] {task_command.py:426} INFO - Running <TaskInstance: my_data_pipeline_dag.collect_data_3 manual__2024-06-06T10:25:06.141092+00:00 [running]> on host DESKTOP-J05K55U.
[2024-06-06T15:55:37.827+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_data_3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T10:25:06.141092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T10:25:06.141092+00:00'
[2024-06-06T15:55:37.828+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T15:55:37.829+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-06T15:55:37.831+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python "/home/wsl/airflow/dags/Collect Data/test.py"']
[2024-06-06T15:55:37.838+0530] {subprocess.py:86} INFO - Output:
[2024-06-06T15:55:47.573+0530] {subprocess.py:93} INFO - 24/06/06 15:55:47 WARN Utils: Your hostname, DESKTOP-J05K55U resolves to a loopback address: 127.0.1.1; using 172.31.56.255 instead (on interface eth0)
[2024-06-06T15:55:47.582+0530] {subprocess.py:93} INFO - 24/06/06 15:55:47 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-06-06T15:55:49.663+0530] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-06-06T15:55:49.663+0530] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-06-06T15:55:50.270+0530] {subprocess.py:93} INFO - 24/06/06 15:55:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-06-06T15:56:01.253+0530] {subprocess.py:93} INFO - <pyspark.sql.session.SparkSession object at 0x7fd55e705ba0>
[2024-06-06T15:56:01.254+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-06-06T15:56:01.254+0530] {subprocess.py:93} INFO -   File "/home/wsl/airflow/dags/Collect Data/test.py", line 11, in <module>
[2024-06-06T15:56:01.254+0530] {subprocess.py:93} INFO -     df_europe = spark.read.format("json").option('multiline', 'true').option("inferschema", 'true').load("europe.json")
[2024-06-06T15:56:01.254+0530] {subprocess.py:93} INFO -   File "/home/wsl/airflow_venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 307, in load
[2024-06-06T15:56:01.256+0530] {subprocess.py:93} INFO -     return self._df(self._jreader.load(path))
[2024-06-06T15:56:01.256+0530] {subprocess.py:93} INFO -   File "/home/wsl/airflow_venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-06-06T15:56:01.259+0530] {subprocess.py:93} INFO -     return_value = get_return_value(
[2024-06-06T15:56:01.259+0530] {subprocess.py:93} INFO -   File "/home/wsl/airflow_venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
[2024-06-06T15:56:01.260+0530] {subprocess.py:93} INFO -     raise converted from None
[2024-06-06T15:56:01.320+0530] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/airflowtmppy_8_xtk/europe.json.
[2024-06-06T15:56:02.259+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-06T15:56:02.260+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T15:56:02.268+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-06T15:56:02.272+0530] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=my_data_pipeline_dag, task_id=collect_data_3, execution_date=20240606T102506, start_date=20240606T102537, end_date=20240606T102602
[2024-06-06T15:56:02.290+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 59 for task collect_data_3 (Bash command failed. The command returned a non-zero exit code 1.; 36667)
[2024-06-06T15:56:02.313+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T15:56:02.325+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T15:56:02.326+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
