[2024-06-14T18:13:12.011+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T18:13:12.031+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_3 manual__2024-06-14T12:42:30.108803+00:00 [queued]>
[2024-06-14T18:13:12.038+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_3 manual__2024-06-14T12:42:30.108803+00:00 [queued]>
[2024-06-14T18:13:12.038+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-06-14T18:13:12.056+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collect_data_3> on 2024-06-14 12:42:30.108803+00:00
[2024-06-14T18:13:12.059+0530] {standard_task_runner.py:63} INFO - Started process 37788 to run task
[2024-06-14T18:13:12.062+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'collect_data_3', 'manual__2024-06-14T12:42:30.108803+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmphqpa0s47']
[2024-06-14T18:13:12.064+0530] {standard_task_runner.py:91} INFO - Job 56: Subtask collect_data_3
[2024-06-14T18:13:12.103+0530] {task_command.py:426} INFO - Running <TaskInstance: my_data_pipeline_dag.collect_data_3 manual__2024-06-14T12:42:30.108803+00:00 [running]> on host DESKTOP-J05K55U.
[2024-06-14T18:13:12.170+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_data_3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T12:42:30.108803+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T12:42:30.108803+00:00'
[2024-06-14T18:13:12.172+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T18:13:12.172+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-14T18:13:12.173+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python "/home/wsl/airflow/dags/Collect Data/test3.py"']
[2024-06-14T18:13:12.179+0530] {subprocess.py:86} INFO - Output:
[2024-06-14T18:13:14.944+0530] {subprocess.py:93} INFO - 24/06/14 18:13:14 WARN Utils: Your hostname, DESKTOP-J05K55U resolves to a loopback address: 127.0.1.1; using 172.31.56.255 instead (on interface eth0)
[2024-06-14T18:13:14.948+0530] {subprocess.py:93} INFO - 24/06/14 18:13:14 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-06-14T18:13:16.242+0530] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/wsl/airflow_venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-06-14T18:13:16.371+0530] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/wsl/.ivy2/cache
[2024-06-14T18:13:16.371+0530] {subprocess.py:93} INFO - The jars for the packages stored in: /home/wsl/.ivy2/jars
[2024-06-14T18:13:16.381+0530] {subprocess.py:93} INFO - org.elasticsearch#elasticsearch-hadoop added as a dependency
[2024-06-14T18:13:16.383+0530] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-28152175-a1a8-4d9b-ae38-a43d937c0396;1.0
[2024-06-14T18:13:16.383+0530] {subprocess.py:93} INFO - 	confs: [default]
[2024-06-14T18:13:16.630+0530] {subprocess.py:93} INFO - 	found org.elasticsearch#elasticsearch-hadoop;8.6.2 in central
[2024-06-14T18:13:16.851+0530] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.1 in central
[2024-06-14T18:13:16.977+0530] {subprocess.py:93} INFO - 	found commons-codec#commons-codec;1.4 in central
[2024-06-14T18:13:17.080+0530] {subprocess.py:93} INFO - 	found javax.xml.bind#jaxb-api;2.3.1 in central
[2024-06-14T18:13:17.306+0530] {subprocess.py:93} INFO - 	found org.apache.hive#hive-service;3.1.2 in central
[2024-06-14T18:13:17.408+0530] {subprocess.py:93} INFO - 	found org.apache.hive#hive-exec;3.1.2 in central
[2024-06-14T18:13:17.456+0530] {subprocess.py:93} INFO - 	found org.apache.hive#hive-metastore;3.1.2 in central
[2024-06-14T18:13:17.485+0530] {subprocess.py:93} INFO - 	found org.apache.pig#pig;0.15.0 in central
[2024-06-14T18:13:17.535+0530] {subprocess.py:93} INFO - 	found org.apache.spark#spark-yarn_2.11;2.3.0 in central
[2024-06-14T18:13:17.561+0530] {subprocess.py:93} INFO - 	found org.scala-lang#scala-reflect;2.11.12 in central
[2024-06-14T18:13:17.591+0530] {subprocess.py:93} INFO - 	found org.apache.storm#storm-core;1.0.6 in central
[2024-06-14T18:13:17.623+0530] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client;3.1.2 in central
[2024-06-14T18:13:17.716+0530] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-common;3.1.2 in central
[2024-06-14T18:13:17.788+0530] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-mapreduce-client-core;3.1.2 in central
[2024-06-14T18:13:17.837+0530] {subprocess.py:93} INFO - 	found joda-time#joda-time;2.9.3 in central
[2024-06-14T18:13:17.921+0530] {subprocess.py:93} INFO - :: resolution report :: resolve 1480ms :: artifacts dl 59ms
[2024-06-14T18:13:17.922+0530] {subprocess.py:93} INFO - 	:: modules in use:
[2024-06-14T18:13:17.922+0530] {subprocess.py:93} INFO - 	commons-codec#commons-codec;1.4 from central in [default]
[2024-06-14T18:13:17.922+0530] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.1 from central in [default]
[2024-06-14T18:13:17.922+0530] {subprocess.py:93} INFO - 	javax.xml.bind#jaxb-api;2.3.1 from central in [default]
[2024-06-14T18:13:17.923+0530] {subprocess.py:93} INFO - 	joda-time#joda-time;2.9.3 from central in [default]
[2024-06-14T18:13:17.923+0530] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client;3.1.2 from central in [default]
[2024-06-14T18:13:17.923+0530] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-common;3.1.2 from central in [default]
[2024-06-14T18:13:17.923+0530] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-mapreduce-client-core;3.1.2 from central in [default]
[2024-06-14T18:13:17.923+0530] {subprocess.py:93} INFO - 	org.apache.hive#hive-exec;3.1.2 from central in [default]
[2024-06-14T18:13:17.924+0530] {subprocess.py:93} INFO - 	org.apache.hive#hive-metastore;3.1.2 from central in [default]
[2024-06-14T18:13:17.924+0530] {subprocess.py:93} INFO - 	org.apache.hive#hive-service;3.1.2 from central in [default]
[2024-06-14T18:13:17.924+0530] {subprocess.py:93} INFO - 	org.apache.pig#pig;0.15.0 from central in [default]
[2024-06-14T18:13:17.924+0530] {subprocess.py:93} INFO - 	org.apache.spark#spark-yarn_2.11;2.3.0 from central in [default]
[2024-06-14T18:13:17.924+0530] {subprocess.py:93} INFO - 	org.apache.storm#storm-core;1.0.6 from central in [default]
[2024-06-14T18:13:17.925+0530] {subprocess.py:93} INFO - 	org.elasticsearch#elasticsearch-hadoop;8.6.2 from central in [default]
[2024-06-14T18:13:17.925+0530] {subprocess.py:93} INFO - 	org.scala-lang#scala-reflect;2.11.12 from central in [default]
[2024-06-14T18:13:17.925+0530] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-06-14T18:13:17.925+0530] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-06-14T18:13:17.926+0530] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-06-14T18:13:17.926+0530] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-06-14T18:13:17.926+0530] {subprocess.py:93} INFO - 	|      default     |   15  |   0   |   0   |   0   ||   15  |   0   |
[2024-06-14T18:13:17.926+0530] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-06-14T18:13:17.940+0530] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-28152175-a1a8-4d9b-ae38-a43d937c0396
[2024-06-14T18:13:17.941+0530] {subprocess.py:93} INFO - 	confs: [default]
[2024-06-14T18:13:17.970+0530] {subprocess.py:93} INFO - 	0 artifacts copied, 15 already retrieved (0kB/30ms)
[2024-06-14T18:13:18.690+0530] {subprocess.py:93} INFO - 24/06/14 18:13:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-06-14T18:13:19.506+0530] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-06-14T18:13:19.506+0530] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-06-14T18:13:21.853+0530] {subprocess.py:93} INFO - 24/06/14 18:13:21 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-06-14T18:13:43.577+0530] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                24/06/14 18:13:43 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-14T18:13:43.652+0530] {subprocess.py:93} INFO - 24/06/14 18:13:43 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-14T18:13:43.676+0530] {subprocess.py:93} INFO - 24/06/14 18:13:43 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-14T18:13:49.194+0530] {subprocess.py:93} INFO - [Stage 3:>                                                          (0 + 3) / 3][Stage 3:===================>                                       (1 + 2) / 3][Stage 3:=======================================>                   (2 + 1) / 3]24/06/14 18:13:49 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-14T18:13:49.195+0530] {subprocess.py:93} INFO - 24/06/14 18:13:49 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-14T18:13:51.483+0530] {subprocess.py:93} INFO - [Stage 5:>                                                          (0 + 1) / 1]                                                                                <pyspark.sql.session.SparkSession object at 0x7f03d2912920>
[2024-06-14T18:13:52.290+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-14T18:13:52.291+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T18:13:57.314+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in xcom_push
    XCom.set(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 222, in set
    dag_run_id = session.query(DagRun.id).filter_by(dag_id=dag_id, run_id=run_id).scalar()
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2893, in scalar
    ret = self.one()
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT dag_run.id AS dag_run_id 
FROM dag_run 
WHERE dag_run.dag_id = ? AND dag_run.run_id = ?]
[parameters: ('my_data_pipeline_dag', 'manual__2024-06-14T12:42:30.108803+00:00')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-14T18:14:00.206+0530] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=my_data_pipeline_dag, task_id=collect_data_3, execution_date=20240614T124230, start_date=20240614T124312, end_date=20240614T124400
[2024-06-14T18:14:00.356+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task collect_data_3 ((sqlite3.OperationalError) database is locked
[SQL: SELECT dag_run.id AS dag_run_id 
FROM dag_run 
WHERE dag_run.dag_id = ? AND dag_run.run_id = ?]
[parameters: ('my_data_pipeline_dag', 'manual__2024-06-14T12:42:30.108803+00:00')]
(Background on this error at: https://sqlalche.me/e/14/e3q8); 37788)
[2024-06-14T18:14:00.591+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T18:14:01.851+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T18:14:01.852+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
